name: ChronoRoot
channels:
  - conda-forge
dependencies:
  - python=3.13.9
  - networkx=3.5
  - pyqt=5.15.11
  - numpy=2.2
  - scikit-image=0.25.2
  - pandas=2.3.3
  - seaborn=0.13.2
  - filterpy=1.4.5
  - lifelines=0.30.0
  - scikit-fda=0.10.1
  - scipy=1.16.3
  - pyzbar=0.1.9
  - pip
  - pip:
    - opencv-python
    - lapx==0.9.2